---

- hosts: all
  become: true
  tasks:

  - name: remove apache / php package on UBUNTU
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache / php package on Redhat
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "RedHat"


