---

- hosts: all
  become: true
  tasks:

  - name: install updates (Redhat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache / php package for Ubuntu Servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for RedHat Servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"
