---
- name: Launch EC2 instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../../vars/aws_vars.yml
  tasks:
    - name: Launch an EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ aws_key_name }}"
        instance_type: "{{ aws_instance_type }}"
        image_id: "{{ aws_ami }}"
        region: "{{ aws_region }}"
        wait: yes
        count: 1
        tags:
          Name: AnsibleProvisionedServer
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groups: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      loop: "{{ ec2.instances }}"

- name: Configure launched instances
  hosts: launched
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
