---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-venv
    - python3-pip
    - nginx
    - git

- name: Clone Flask app repository
  git:
    repo: 'https://github.com/aaronlmathis/flaskapp.git'
    dest: /home/ubuntu/flaskapp
    version: main

- name: Create a virtual environment for Flask app
  command:
    cmd: python3 -m venv /home/ubuntu/flaskapp/venv
    creates: /home/ubuntu/flaskapp/venv

- name: Install Gunicorn in virtual environment
  pip:
    name: gunicorn
    virtualenv: /home/ubuntu/flaskapp/venv

- name: Install Flask requirements in virtual environment
  pip:
    requirements: /home/ubuntu/flaskapp/requirements.txt
    virtualenv: /home/ubuntu/flaskapp/venv

- name: Ensure correct ownership of Flask app directory
  file:
    path: /home/ubuntu/flaskapp
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: Configure Gunicorn systemd service
  template:
    src: flask_app.service.j2
    dest: /etc/systemd/system/flask_app.service

- name: Start and enable Gunicorn service
  systemd:
    name: flask_app
    state: started
    enabled: yes

- name: Configure Nginx
  template:
    src: nginx_flask.j2
    dest: /etc/nginx/sites-available/flask_app

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/flask_app
    dest: /etc/nginx/sites-enabled/flask_app
    state: link

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
