---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-dev
    - nginx
    - git
    - python3-venv

- name: Clone Flask app repository
  git:
    repo: 'https://github.com/bohwaz/flask-app-example.git'
    dest: /home/ubuntu/flaskapp

- name: Create a virtual environment for Flask app
  command: python3 -m venv /home/ubuntu/flaskapp/venv

- name: Install Gunicorn and Flask requirements in virtual environment
  command: /home/ubuntu/flaskapp/venv/bin/pip install -r /home/ubuntu/flaskapp/requirements.txt

- name: Configure Gunicorn systemd service
  template:
    src: flask_app.service.j2
    dest: /etc/systemd/system/flask_app.service

- name: Start and enable Gunicorn service
  systemd:
    name: flask_app
    state: started
    enabled: yes

- name: Configure Nginx
  template:
    src: nginx_flask.j2
    dest: /etc/nginx/sites-available/flask_app

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/flask_app
    dest: /etc/nginx/sites-enabled/flask_app
    state: link

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
